virtual-kubelet/tensile-kube

cmd/provider/main.go, pkg/controllers/common_controller.go, pkg/provider/pod.go, pkg/util/k8s.go
Bugfix: pv resource update failed
Support configmap/secret update
=> Bugfix: pv resource/configmap/secret update failed 

pkg/scheduler/multischeduler/scheduler.go
=> fix podCopy.Spec.Affinity

pkg/testbase/test.go, pkg/webhook/hook.go, pkg/webhook/hook_test.go
Allow pass ignore-labels to nodeAffinity
=> Allow pass ignore-labels to nodeAffinity

pkg/scheduler/multischeduler/scheduler.go, pkg/testbase/test.go, pkg/util/conversions.go, pkg/webhook/hook.go, pkg/webhook/hook_test.go
Refactor logic about ignore-selector-keys
=> Refactor logic about ignore-selector-keys

pkg/controllers/common_controller.go, pkg/provider/pod.go
1. add addFunc
2. remove logic about update int provider
=> Add addFunc to ensure configmap/secret update

cmd/provider/main.go, pkg/provider/pod.go, pkg/provider/provider.go, pkg/webhook/hook.go
Add flag enableServiceAccount to make it possible to use enableServiceAccount
=> Add flag enableServiceAccount

pkg/common/node.go, pkg/common/resource.go, pkg/controllers/common_controller.go, pkg/provider/node.go, pkg/provider/pod.go, pkg/provider/provider.go
1. fix quota computation
2. fix secret update
=> Bugfix: quota computation not correctly

hack/virtual-node.yaml, pkg/provider/node.go
1. Enable internal ip
2. Add a example of deployment
=> Add example of run virtual-node in cluster

pkg/controllers/common_controller.go, pkg/controllers/common_controller_test.go, pkg/controllers/service_controller.go, pkg/controllers/service_controller_test.go
1. Add unit test for service_controller
2. Minorly change logic of common controller
=> Add unit tests for controllers

pkg/webhook/hook.go
Filter empty NodeSelectorTerms
=> Bugfix: Filter empty SelectorTerms

pkg/provider/helper.go
Fix: https://github.com/virtual-kubelet/tensile-kube/issues/31
=> Bugfix: fix using secret of cinder, rbd bug

ADOPTERS.md, pkg/controllers/common_controller_test.go, pkg/provider/helper.go
vk has convert the values to env directly
=> do not sync secret and configmap from env

README.md
=> Add other contributors

pkg/provider/node.go, pkg/provider/pod.go, pkg/provider/provider.go, pkg/scheduler/config/config.go, pkg/scheduler/multischeduler/scheduler.go
Change ping logic and remove some useless todo
=> Change ping logic and remove some todo

pkg/descheduler/descheduler.go, pkg/descheduler/evictions/cache.go, pkg/descheduler/evictions/evictions.go, pkg/descheduler/strategies/pod_lifetime.go
accelerate evict for descheduler
=> accelerate evict

pkg/descheduler/descheduler.go, pkg/descheduler/evictions/evictions.go, pkg/descheduler/evictions/evictions_test.go, pkg/util/cache.go, pkg/util/cache_test.go, pkg/webhook/hook.go
Move unschedulable nodes logic to webhook
=> Webhook inject unschedulable nodes

cmd/provider/main.go, pkg/controllers/common_controller.go, pkg/controllers/common_controller_test.go, pkg/util/cache.go, pkg/webhook/hook.go
=> Fix some lints

.github/workflows/go.yml, pkg/controllers/common_controller.go, pkg/controllers/common_controller_test.go, pkg/controllers/service_controller.go, pkg/controllers/service_controller_test.go, pkg/controllers/utils.go
Fix unit tests, unit may fail some times
=> Fix unit tests

go.mod, go.sum
See this issue 
https://github.com/evanphx/json-patch/issues/106
Seem a bug in github.com/mattbaird/jsonpatch
We have opened a PR https://github.com/mattbaird/jsonpatch/pull/29 to fix this , but before this, we switch dependency to `github.com/cwdsuzhou/jsonpatch` temporarily
=> Update dependency to fix potential panic

pkg/util/k8s.go
Fix https://github.com/virtual-kubelet/tensile-kube/issues/46
=> remove tencent batch label

pkg/util/util.go
fix pod request according to kubernetes which initContainers and PodOverhead should be calculated.
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/resource/helpers.go#L35-L72
=> fix pod request according to kubernetes
